services:
  backend-users:
    build:
      context: .
      dockerfile: ./rpl_users/Dockerfile
    restart: always
    ports:
      - 8000:80
    env_file:
      - path: ./rpl_users/.env
        required: true
  # backend-activities:
  #   build:
  #     context: .
  #     dockerfile: ./rpl_activities/Dockerfile
  #   restart: always
  #   ports:
  #     - 8001:80
  #   env_file:
  #     - path: ./rpl_activities/.env
  #       required: true

