services:
  backend-users:
    build:
      context: ./users
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
  
  # backend-activities:
  #   build:
  #     context: ./activities
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 8000:8001
  #   environment:
  #     - MYSQL_HOST=${MYSQL_HOST}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_DB=${MYSQL_DB}
      
