services:
  backend-users:
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
      - MYSQL_DB=test_db
  
  # backend-activities:
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_USER=test_user
  #     - MYSQL_PASSWORD=test_password
  #     - MYSQL_DB=test_db
