services:
  users_api:
    build:
      context: .
      dockerfile: ./rpl_users/Dockerfile
    restart: always
    ports:
      - "8000:80"
    env_file:
      - path: ./rpl_users/.env
        required: true
    volumes:
        - ./rpl_users/src:/rpl_users/src
    networks:
      - localrpl_net
      - rpl3_backend_localdb_net
  activities_api:
    build:
      context: .
      dockerfile: ./rpl_activities/Dockerfile
    restart: always
    ports:
      - "8001:80"
    env_file:
      - path: ./rpl_activities/.env
        required: true
    volumes:
      - ./rpl_activities/src:/rpl_activities/src
    networks:
      - localrpl_net
      - rpl3_backend_localdb_net

networks:
  localrpl_net:
    driver: bridge

  rpl3_backend_localdb_net:
    external: true


