services:
  # local_db:
  #   build:
  #     context: ./mysql/mysql80
  #     dockerfile: mysql80.Dockerfile
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_USER: test_user
  #     MYSQL_PASSWORD: test_password
  #   volumes:
  #     - ./mysql/mysql80_data_vol:/var/lib/mysql
  #   ports:
  #     - "33068:3306"
  #   networks:
  #     - localdb_net
  latest_db:
    build:
      context: ./mysql/mysql84
      dockerfile: mysql84.Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql/mysql84_data_vol:/var/lib/mysql
    ports:
      - "33069:3306"
    networks:
      - localdb_net

networks:
  localdb_net:
    driver: bridge