services:
  local_updated_db:
    build:
      context: ./mysql80
      dockerfile: mysql80.Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql_updated_data:/var/lib/mysql
    ports:
      - "33068:3306"
