USE rpl_users;
RENAME TABLE validation_token TO validation_tokens;
ALTER TABLE validation_tokens RENAME COLUMN expiry_date TO expiration_date;
DELETE FROM validation_tokens WHERE expiration_date < CURDATE();
ALTER TABLE courses RENAME COLUMN university_course_id TO subject_id;
ALTER TABLE courses RENAME COLUMN semester_END_date TO semester_end_date;
UPDATE roles SET name = 'course_admin', last_updated = UTC_TIMESTAMP() WHERE id=1;
INSERT INTO universities (id, name, degrees) VALUES (1, 'FIUBA', 'Ingeniería en Informática,Licenciatura en Sistemas,Ingeniería Civil,Ingeniería de Alimentos,Ingeniería Electricista,Ingeniería Electrónica,Ingeniería en Agrimensura,Ingeniería en Petróleo,Ingeniería Industrial,Ingeniería Mecánica,Ingeniería Naval y Mecánica,Ingeniería Química');

USE rpl_activities;
ALTER TABLE activities RENAME COLUMN starting_files_id TO starting_rplfile_id;
ALTER TABLE activities RENAME COLUMN activity_category_id TO category_id;
ALTER TABLE activities ADD UNIQUE (starting_rplfile_id);
RENAME TABLE unit_test_run TO unit_test_runs, io_test_run TO io_test_runs, test_run TO tests_execution_logs;
ALTER TABLE unit_test_runs RENAME COLUMN name TO test_name;
RENAME TABLE unit_tests TO unit_test_suites;
ALTER TABLE unit_test_suites ADD UNIQUE (activity_id);
ALTER TABLE unit_test_suites RENAME COLUMN test_file_id TO test_rplfile_id;
ALTER TABLE unit_test_suites ADD UNIQUE (test_rplfile_id);
ALTER TABLE activity_submissions RENAME COLUMN response_files_id TO solution_rplfile_id;
ALTER TABLE activity_submissions ADD UNIQUE (solution_rplfile_id);
DROP TABLE IF EXISTS results;
