services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - devcontainer_net
      # - rpl3_backend_localdb_net # Requires the local db container to be running (latest_db at metaservices.local.yml). USEFUL FOR MIGRATIONS
    command: sleep infinity

networks:
  devcontainer_net:
    driver: bridge
    
  
  # rpl3_backend_localdb_net:  # Requires the local db container to be running (latest_db at metaservices.local.yml). USEFUL FOR MIGRATIONS
  #   external: true
