services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/dev.Dockerfile
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "9000:80"
    networks:
      - dev_network
      # - rpl3_backend_default # Requires the local db container to be running (latest_db at metaservices.local.yml). USEFUL FOR MIGRATIONS
    command: sleep infinity

networks:
  dev_network:
    driver: bridge
    
  
  # rpl3_backend_default:  # Requires the local db container to be running (latest_db at metaservices.local.yml). USEFUL FOR MIGRATIONS
  #   external: true
