services:
  dev_db:
    image: mysql:8.0.37
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql_test_data:/var/lib/mysql
    networks:
      - dev_network
    ports:
      - "3306:3306"

networks:
  dev_network:
    driver: bridge

