services:
  dev_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql_test_data:/var/lib/mysql
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

