services:
  testing_db:
    image: mysql:8.4.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./mysql_test_data:/var/lib/mysql
      - ./db_test_config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev_network
    ports:
      - "3306:3306"

networks:
  dev_network:
    driver: bridge

