apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
  labels:
    app: rabbitmq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9419"
    spec:
      containers:
        - name: rabbitmq-exporter
          image: kbudde/rabbitmq-exporter:v1.2.0
          ports:
            - containerPort: 9419
          env:
            env:
            - name: RABBIT_URL
              value: http://queue:15672
            - name: RABBIT_USER
              value: guest
            - name: RABBIT_PASSWORD
              value: guest
            - name: PUBLISH_PORT
              value: "9419"