apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpl-activities-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rpl-activities-api
      tier: backend
      track: stable
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        app: rpl-activities-api
        tier: backend
        track: stable
    spec:
      containers:
      - name: rpl-activities-api
        image: gcr.io/rpl2-fiuba/rpl-3.0-activities:latest #  rpl-activities-api:local
        env:
        - name: FASTAPI_PRODUCTION_PROFILE
          value: "true"
        - name: FRONTEND_URL
          value: "https://myrpl.ar"
        - name: USERS_API_URL
          value: "http://rpl-users-api"
        - name: QUEUE_URL
          value: "amqp://guest:guest@queue:5672"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: activities-db-url
              key: activities-db-url
        - name: RUNNER_API_KEY
          valueFrom:
            secretKeyRef:
              name: runner-api-key
              key: runner-api-key
        ports:
          - name: http
            containerPort: 80
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          httpGet:
            path: /api/v3/health
            port: 80
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 3
          httpGet:
            path: /api/v3/health
            port: 80
        resources:
          requests:
            cpu: 25m
            memory: 256Mi
          limits:
            memory: 512Mi