apiVersion: v1
kind: Service
metadata:
  name: rpl-users-api
spec:
  type: NodePort
  selector:
    app: rpl-users-api
    tier: backend
  ports:
    - nodePort: 30001
      port: 80
      protocol: TCP